refactor(airdrop contracts): New world-id-contracts change the API required for the airdrop contracts
worldcoin/world-id-example-airdrop pull request #31
Opened 2023-04-07 09:34 UTC by dcbuild3r

Addresses issue #30. 

The new [world-id-contracts](https://github.com/worldcoin/world-id-contracts/) use [Semaphore v3](https://github.com/worldcoin/semaphore-v3/) and the API changes slightly.

Changes that need to be made:
- [ ] Update the `verifyProof` function to match the new `world-id-contracts`
- [ ] Update tests to not have to use Semaphore (mock verification)
- [ ] Create Forge scripts to deploy the contracts
- [ ] modify `deploy.js` to call forge scripts instead

2023-04-10 17:25 UTC, iamrecursion requested changes
A good start, but more work needed.

2023-04-11 17:12 UTC, dcbuild3r commented on src/WorldIDAirdrop.sol
>      /// @param _groupId The ID of the Semaphore group World ID is using (`1`)
This will depend on a live deployment, we can document this after the fact. This will need a decision from the protocol and app teams @philsippl .

2023-04-11 17:30 UTC, dcbuild3r reviewed
All reviewed.

2023-04-11 17:31 UTC, iamrecursion approved these changes
LGTM. Let's get this merged and give Nethermind a commit hash.

2023-04-11 17:32 UTC, merged